### PR TITLE
added intel pickup and drop sounds

### PR DESCRIPTION
**Pull request by NotAFile**
This PR contains less than I wanted, but at least _some_ sound on intel pickup and drop are a big improvement. I hope to be adding capture sounds and a win fanfare soon.

### CODE REVIEW

**Comment by iamgreaser** [comment]
Most non-ADPCM wav files we have:

```
Stream #0:0: Audio: pcm_u8 ([1][0][0][0] / 0x0001), 22050 Hz, 1 channels, u8, 176 kb/s
```

These files:

```
Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 1 channels, s16, 705 kb/s
```

Although two other files seem to also be this size.

It's probably best to just push it anyway and then I can convert them to the appropriate sizes/formats (I use SoX to convert them, if you were to naively convert them you'd ruin the quality as e.g. ffmpeg does a terrible job of downsampling), and also get ADPCM versions up.

**Comment by NotAFile** [comment]
I previously had them as 8bit, as converted by ffmpeg, which sounded okay. If you are concerned about size, I'm not sure shaving a total of 120K off two soundfiles is the best place to do that, (especially when gzipping would halve the size of `pkg/` and files could be cached) although every little helps, and it's not like the fidelity of the crappy marimbaphone sample I used matters anyway.

I could do the SoX stuff myself if I read the docs enough.

**Comment by iamgreaser** [comment]
That 120KB is actually pretty important, as not everybody has a high upload speed. Also, gzipping won't halve the size of the wav files, we already have fastload for bundling stuff into one package, and Iceball uses the same compression algorithm that gzip uses when sending files anyway.

Here's what you need:

```
sox input.wav -D -b 8 -c 1 -r 22050 wav/output.wav
```

And for ADPCM:

```
sox input.wav -D -e ima-adpcm -c 1 -r 44100 adpcm/output.wav
```

**Comment by rakiru** [comment]
Note to whoever merges: please squash the commits, since one is just a fix for the other.

**Comment by iamgreaser** [comment]
Mind producing the ADPCM versions too? Use the 44kHz 16-bit versions as your base.

EDIT: Oh fuck. All these years and I never pushed `pkg/base/adpcm`.

**Comment by rakiru** [comment]
We should just move all files in `adpcm/` to `wav/`, then remove any code that references `adpcm/`. We're breaking things anyway, and ADPCM support has existed for a while.

Since these are new files, this should be good to merge once the ADPCM sounds are pushed instead.

**Comment by NotAFile** [comment]
It's been decided that I reapply the the changes on the current dev branch and open a new PR for a cleaner merge

**Pull request closed without merging**
