### PR TITLE
portalgun: Change colors on fire

### PR DESCRIPTION
**Pull request by 10se1ucgo**
Also fix an (accidental?) global.

### CODE REVIEW

**Comment by iamgreaser** [comment]
Looking at this, could you please just make it generate the two models ONCE during mod init, and then switch between the two models?

Make sure it only happens once, and not every time someone spawns or anything like that (_cough_ 1.x lasersights _cough_).

**Comment by 10se1ucgo** [comment]
In hindsight that sounds much smarter :P Will do.

**Comment by 10se1ucgo** [comment]
Is that what you were looking for?

**Comment by iamgreaser** [comment]
Yeah, that should work.

**Pull request merged**
